valid_extensions:
- ".avi"
- ".mkv"
- ".mp4"

# Log
log: false

# Email
email: false
email_to: ""
email_from: ""
email_smtp_user: ""
email_smtp_password: ""
email_smtp_host: "smtp.gmail.com"
email_smtp_port: 587

# Melyik feliratos oldalt vizsgaljuk
dl_subirat: true
dl_feliratok: true
dl_hosszupuskasub: true

# Miutan szetbontottuk a fajl nevet akkor ezeket a dolgokat csereljuk a kulonbozo reszekben.
extra_info_replacements:
  - replacement: ""
    match: "[hH][eE][vV][cC][. ]26[45]"
    is_regex: true
  - replacement: ""
    match: "[xXhH](.?| ?)26[45]"
    is_regex: true
  - replacement: ""
    match: "(AAC|DD)[+][25][. ][01]"
    is_regex: true
  - replacement: ""
    match: "[xX][vV][iI][dD]"
    is_regex: true
  - replacement: ""
    match: "READNFO"
    is_regex: true
  - replacement: ""
    match: "[aA][mM][zZ][nN]"
    is_regex: true
  - replacement: ""
    match: "[hH][bB][oO]"
    is_regex: true
  - replacement: "720p"
    match: "720[pP][. ][hH][dD][tT][vV]"
    is_regex: true
  - replacement: "1080p"
    match: "1080[pP][. ][hH][dD][tT][vV]"
    is_regex: true
  - replacement: "720p"
    match: "720[pP]([. ]*|)[wW][eE][bB][rR][iI][pP]|720[pP]([. ]*|)[wW][eE][bB]-[dD][lL]|720[pP]([. ]*|)[wW]eE[bB]"
    is_regex: true
  - replacement: ""
    match: " "
    is_regex: true

releasegroup_info_replacements:
  - replacement: ""
    match: "[(\\[].*[)\\]]"
    is_regex: true
  - replacement: ""
    match: "[tT][bB][sS]"
    is_regex: true

seriesname_replacements:
  # A The Bridge sorozat miatt kell hogy a US vegzodest toroljuk mert nem ismeri fel a sorozatos oldal
  - replacement: ""
    match: " [Uu][Ss]"
    is_regex: true
  # Ha elrontanak a fajl nevet es a sorozat neveben bennemaradnak akkor ezeket torolni kell.
  - replacement: ""
    match: "[pP][rR][oO][pP][eE][rR]"
    is_regex: true
  - replacement: ""
    match: "[rR][eE][pP][aA][cC][kK]"
    is_regex: true


# Ha nem ures akkor az itt megadott infok alapjan tiltunk fajl neveket, pelda:
# [{is_regex: true, match: ".*sample.*"}, {is_regex: false, match: "sample"}]
filename_blacklist:
  - is_regex: true
    match: ".*sample.*"
  - is_regex: true
    match: ".*[.-][hH][uU][nN][.-].*"
    full_path: true


# A kiterjeszteseknel neha el kell tavolitani a nyelvet erre valo ez, pelda:
# extension_pattern: "(\.(eng|cze))?(\.[a-zA-Z0-9]+)$"
# ezt "foo.eng.srt" erre bontja  "foo" es ".eng.srt".
extension_pattern: "(\\.[a-zA-Z0-9]+)$"
# Ha a sorozat cime is szerepelne a fajl neveben akkor azt ki kell torolni.
extra_info_pattern: "^(?P<extra>.*(720p|720i|1080p|1080i)|.*(HDTV|WEBRip|DVDRip|WEBDL|TVRip))$"

# Seasonpack kezelese:
valid_subextensions:
  - "srt"

dl_season: false
recursive: false

dir_pattern: "[^\\/]+(?=\\/$|$)"

seasonpack_pattern: "^((?P<seriesname>.+?)[ \\._\\-])?\\[?[Ss](?P<seasonnumber>[0-9]+)[ ]?[\\._\\- ]?[ ]?((?P<extrainfo>.+?)(-(?P<releasegroup>[^-]+)))$"

# Fajlok szetbontasa talalhato itt:
filename_patterns:
  # foo.s01e23e24*
  - "^((?P<seriesname>.+?)[ \\._\\-])?[Ss](?P<seasonnumber>[0-9]+)[\\.\\- ]?[Ee](?P<episodenumberstart>[0-9]+)([\\.\\- ]?[Ee][0-9]+)*[\\.\\- ]?[Ee](?P<episodenumberend>[0-9]+)[\\.\\- ]((?P<extrainfo>.+?)(-(?P<releasegroup>[^-]+))?\\.(?P<extension>[^.]+)?)?$"
  # foo.1x23x24*
  - "^((?P<seriesname>.+?)[ \\._\\-])?(?P<seasonnumber>[0-9]+)[xX](?P<episodenumberstart>[0-9]+)([xX][0-9]+)*[xX](?P<episodenumberend>[0-9]+)[\\.\\- ]((?P<extrainfo>.+?)(-(?P<releasegroup>[^-]+))?\\.(?P<extension>[^.]+)?)?$"
  # foo.s01e23-24*
  - "^((?P<seriesname>.+?)[ \\._\\-])?[Ss](?P<seasonnumber>[0-9]+)[\\.\\- ]?[Ee](?P<episodenumberstart>[0-9]+)([\\-][Ee]?[0-9]+)*[\\-][Ee]?(?P<episodenumberend>[0-9]+)[\\.\\- ]((?P<extrainfo>.+?)(-(?P<releasegroup>[^-]+))?\\.(?P<extension>[^.]+)?)?$"
  # foo.1x23-24*
  - "^((?P<seriesname>.+?)[ \\._\\-])?(?P<seasonnumber>[0-9]+)[xX](?P<episodenumberstart>[0-9]+)([\\-+][0-9]+)*[\\-+](?P<episodenumberend>[0-9]+)[\\.\\- ]((?P<extrainfo>.+?)(-(?P<releasegroup>[^-]+))?\\.(?P<extension>[^.]+)?)?$"
  # foo.1x09*
  - "^((?P<seriesname>.+?)[ \\._\\-])?\\[?(?P<seasonnumber>[0-9]+)[xX](?P<episodenumber>[0-9]+)[\\.\\- ]((?P<extrainfo>.+?)(-(?P<releasegroup>[^-]+))?\\.(?P<extension>[^.]+)?)?$"
  # foo.s01.e01, foo.s01_e01, "foo.s01 - e01"
  - "^((?P<seriesname>.+?)[ \\._\\-])?\\[?[Ss](?P<seasonnumber>[0-9]+)[ ]?[\\._\\- ]?[ ]?[Ee]?(?P<episodenumber>[0-9]+)[\\.\\- ]((?P<extrainfo>.+?)(-(?P<releasegroup>[^-]+))?\\.(?P<extension>[^.]+)?)?$"
  # foo.103*
  - "^(?P<seriesname>.+)[ \\._\\-](?P<seasonnumber>[0-9]{1})(?P<episodenumber>[0-9]{2})[\\.\\- ]((?P<extrainfo>.+?)(-(?P<releasegroup>[^-]+))?\\.(?P<extension>[^.]+)?)?$"
  # foo.0103*
  - "^(?P<seriesname>.+)[ \\._\\-](?P<seasonnumber>[0-9]{2})(?P<episodenumber>[0-9]{2})[\\.\\- ]((?P<extrainfo>.+?)(-(?P<releasegroup>[^-]+))?\\.(?P<extension>[^.]+)?)?$"
  # foo.10304*
  - "^(?P<seriesname>.+)[ \\._\\-](?P<seasonnumber>[0-9]{1})(?P<episodenumberstart>[0-9]{2})(?P<episodenumberend>[0-9]{2})[\\.\\- ]((?P<extrainfo>.+?)(-(?P<releasegroup>[^-]+))?\\.(?P<extension>[^.]+)?)?$"
  # show.name.e123.abc
  - "^(?P<seriesname>.+?)[ \\._\\-][Ee](?P<episodenumber>[0-9]+)((?P<extrainfo>.+?)(-(?P<releasegroup>[^-]+))?\\.(?P<extension>[^.]+)?)?$"

# A sorozat neveben ha van datum azt el kell valasztani tole
seriesname_year_pattern: "^((?P<seriesname>.+?)[ ])?(?P<year>(19|20)\\d{2}?)?$"
# subirat.net oldalhoz kell a sorozat es az epizos sorszam olvasashoz
subirat_pattern: "(.vad: (?P<seasonnumber>[0-9]+).+)?(Epiz.d: (?P<episodenumber>[0-9]+).+)"

# feliratok.info nyelv meghatarozashoz, pelda: Angol, 2
language: "Magyar"
language_number: "1"

# A plex miatt a letoltott feliratokhoz hozzatesszuk a nyelvet
language_sub: "HU"
subtitle_extension: "srt"

# Az epizod sorszama mindig 2 karakteres legyen
episode_number: "%02s"
